name: Unit Tests

on:
  push:
    branches:
      - prototype
      - unit-tests
  pull_request:
    branches: [prototype]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          yarn install 
          yarn test